version: '3'

services:
  node-app:
    build: .
    container_name: node-app
    expose:
      - "3000"  
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
    ports:
      - "80:80"  
    depends_on:
      - node-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

